### ISSUE TITLE
Deletion of downloaded file

### ISSUE THREAD

**Issue by Napkin** [oleerik/hex-linux-launcher#9]
Would be nice if the tarball could be automatically deleted after successful extraction. Thanks!

**Comment by lillelilje** [comment]
Right, shouldn't be an issue to add at all. Thank you!

**Comment by lillelilje** [comment]
Added a very simple way of doing it. No check for successful extraction first yet, but the chance of the extraction failing is low to nonexistent. 3d3484892ebf416a6fcc31f32de536fcd633a945

**Comment by Napkin** [comment]
Only case I could imagine for now is if there is not enough free space. I saw you adding a check for that earlier. Should be OK then. Great, thanks!
